/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gims.design;

/**
 *
 * @author sukumar sen
 */
public class FeeRecordsSheet extends javax.swing.JPanel {

    /**
     * Creates new form FeeRecordsSheet
     */
    public FeeRecordsSheet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCourse = new javax.swing.JComboBox();
        lblAge = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblPanelHeader = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        cmbAdmission = new javax.swing.JComboBox();
        lblCategory = new javax.swing.JLabel();
        cmbCategory1 = new javax.swing.JComboBox();
        txtAdmission = new javax.swing.JTextField();
        lblUniversity1 = new javax.swing.JLabel();
        cmbUniversity1 = new javax.swing.JComboBox();
        lblEmail = new javax.swing.JLabel();
        lblAdmissionNo1 = new javax.swing.JLabel();
        txtMobileAlternate = new javax.swing.JTextField();
        lblStudent2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblExamFee = new javax.swing.JLabel();
        txtMobile2 = new javax.swing.JTextField();
        lblMobileAlternate1 = new javax.swing.JLabel();
        txtAdmission3 = new javax.swing.JTextField();
        lblMobile3 = new javax.swing.JLabel();
        txtAdmission4 = new javax.swing.JTextField();
        txtTotalAmt = new javax.swing.JTextField();
        lblRemainingAmt = new javax.swing.JLabel();
        lblTotalFee2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblfeeDetail1 = new javax.swing.JLabel();
        txtAdmission6 = new javax.swing.JTextField();
        lblTotalAmount1 = new javax.swing.JLabel();
        txtTotalAmt1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCourseActionPerformed(evt);
            }
        });
        add(cmbCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 200, 28));

        lblAge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText("Age");
        lblAge.setToolTipText("");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, 30));

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gims/resource/close.png"))); // NOI18N
        add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 25, 25));

        lblPanelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gims/resource/glossPanelHeader.png"))); // NOI18N
        lblPanelHeader.setToolTipText("");
        add(lblPanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        lblCourse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCourse.setForeground(new java.awt.Color(255, 255, 255));
        lblCourse.setText("Course");
        lblCourse.setToolTipText("");
        add(lblCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, 30));

        cmbAdmission.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbAdmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 200, 28));

        lblCategory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblCategory.setText("Category");
        lblCategory.setToolTipText("");
        add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, 30));

        cmbCategory1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbCategory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 110, 28));
        add(txtAdmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 40, 26));

        lblUniversity1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUniversity1.setForeground(new java.awt.Color(255, 255, 255));
        lblUniversity1.setText("University");
        lblUniversity1.setToolTipText("");
        add(lblUniversity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 30));

        cmbUniversity1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbUniversity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 170, 28));

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        lblEmail.setToolTipText("");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, 30));

        lblAdmissionNo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAdmissionNo1.setForeground(new java.awt.Color(255, 255, 255));
        lblAdmissionNo1.setText("Admission No");
        lblAdmissionNo1.setToolTipText("");
        add(lblAdmissionNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, 30));

        txtMobileAlternate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMobileAlternate.setText("0123456789");
        add(txtMobileAlternate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 90, 26));

        lblStudent2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStudent2.setForeground(new java.awt.Color(255, 255, 255));
        lblStudent2.setText("Student");
        lblStudent2.setToolTipText("");
        add(lblStudent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 30));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 260, 26));

        lblExamFee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblExamFee.setForeground(new java.awt.Color(255, 255, 255));
        lblExamFee.setText("Exam Fee");
        lblExamFee.setToolTipText("");
        add(lblExamFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, 30));

        txtMobile2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMobile2.setText("0123456789");
        add(txtMobile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 90, 26));

        lblMobileAlternate1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMobileAlternate1.setForeground(new java.awt.Color(255, 255, 255));
        lblMobileAlternate1.setText("Alternate No");
        lblMobileAlternate1.setToolTipText("");
        add(lblMobileAlternate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 30));

        txtAdmission3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAdmission3.setText("12345678");
        add(txtAdmission3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 90, 26));

        lblMobile3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMobile3.setForeground(new java.awt.Color(255, 255, 255));
        lblMobile3.setText("Mobile No");
        lblMobile3.setToolTipText("");
        add(lblMobile3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));
        add(txtAdmission4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 170, 26));

        txtTotalAmt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotalAmt.setText("12345678");
        txtTotalAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalAmtActionPerformed(evt);
            }
        });
        add(txtTotalAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 100, 26));

        lblRemainingAmt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRemainingAmt.setForeground(new java.awt.Color(255, 255, 255));
        lblRemainingAmt.setText("Remaining Amount");
        lblRemainingAmt.setToolTipText("");
        add(lblRemainingAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, 20));

        lblTotalFee2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalFee2.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalFee2.setText("Total course Fee");
        lblTotalFee2.setToolTipText("");
        add(lblTotalFee2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 730, 150));

        lblfeeDetail1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblfeeDetail1.setForeground(new java.awt.Color(255, 255, 255));
        lblfeeDetail1.setText("Fee Detail");
        lblfeeDetail1.setToolTipText("");
        add(lblfeeDetail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 20));

        txtAdmission6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAdmission6.setText("12345678");
        add(txtAdmission6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, 26));

        lblTotalAmount1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalAmount1.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalAmount1.setText("Total Amount");
        lblTotalAmount1.setToolTipText("");
        add(lblTotalAmount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, 20));

        txtTotalAmt1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotalAmt1.setText("12345678");
        add(txtTotalAmt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 100, 26));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCourseActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTotalAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalAmtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbAdmission;
    private javax.swing.JComboBox cmbCategory1;
    private javax.swing.JComboBox cmbCourse;
    private javax.swing.JComboBox cmbUniversity1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAdmissionNo1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblExamFee;
    private javax.swing.JLabel lblMobile3;
    private javax.swing.JLabel lblMobileAlternate1;
    private javax.swing.JLabel lblPanelHeader;
    private javax.swing.JLabel lblRemainingAmt;
    private javax.swing.JLabel lblStudent2;
    private javax.swing.JLabel lblTotalAmount1;
    private javax.swing.JLabel lblTotalFee2;
    private javax.swing.JLabel lblUniversity1;
    private javax.swing.JLabel lblfeeDetail1;
    private javax.swing.JTextField txtAdmission;
    private javax.swing.JTextField txtAdmission3;
    private javax.swing.JTextField txtAdmission4;
    private javax.swing.JTextField txtAdmission6;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobile2;
    private javax.swing.JTextField txtMobileAlternate;
    private javax.swing.JTextField txtTotalAmt;
    private javax.swing.JTextField txtTotalAmt1;
    // End of variables declaration//GEN-END:variables
}
