/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gims.design;

/**
 *
 * @author sukumar sen
 */
public class GimsLogin extends javax.swing.JFrame {

    /**
     * Creates new form GimsLogin
     */
    public GimsLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanelMain = new javax.swing.JPanel();
        loginTabPanel = new javax.swing.JTabbedPane();
        loginAdminPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtAdminUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAdminPassword = new javax.swing.JPasswordField();
        btnAdminOk = new javax.swing.JButton();
        btnAdminCancel = new javax.swing.JButton();
        lblLock = new javax.swing.JLabel();
        loginUserPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtUserUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUserPassword = new javax.swing.JPasswordField();
        btnUserOK = new javax.swing.JButton();
        btnUserCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GIMS V1.0");
        setMinimumSize(new java.awt.Dimension(400, 300));

        loginPanelMain.setBackground(new java.awt.Color(153, 204, 255));
        loginPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTabPanel.setBackground(new java.awt.Color(153, 204, 255));
        loginTabPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginTabPanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        loginAdminPanel.setBackground(new java.awt.Color(153, 204, 255));
        loginAdminPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginAdminPanel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginAdminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("User");
        loginAdminPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 30, -1, -1));

        txtAdminUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginAdminPanel.add(txtAdminUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Password");
        loginAdminPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 68, -1, 30));
        loginAdminPanel.add(txtAdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 150, -1));

        btnAdminOk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdminOk.setText("OK");
        btnAdminOk.setMaximumSize(new java.awt.Dimension(49, 20));
        btnAdminOk.setMinimumSize(new java.awt.Dimension(49, 20));
        btnAdminOk.setPreferredSize(new java.awt.Dimension(49, 20));
        loginAdminPanel.add(btnAdminOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 138, 60, 35));

        btnAdminCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdminCancel.setText("Cancel");
        btnAdminCancel.setMaximumSize(new java.awt.Dimension(71, 20));
        btnAdminCancel.setMinimumSize(new java.awt.Dimension(71, 20));
        btnAdminCancel.setPreferredSize(new java.awt.Dimension(71, 20));
        loginAdminPanel.add(btnAdminCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 138, 90, 35));

        lblLock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gims/resource/padlock.png"))); // NOI18N
        loginAdminPanel.add(lblLock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 90, 90));

        loginTabPanel.addTab("Admin", loginAdminPanel);

        loginUserPanel.setBackground(new java.awt.Color(153, 204, 255));
        loginUserPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginUserPanel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("User");

        txtUserUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Password");

        btnUserOK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUserOK.setText("OK");
        btnUserOK.setMaximumSize(new java.awt.Dimension(49, 20));
        btnUserOK.setMinimumSize(new java.awt.Dimension(49, 20));
        btnUserOK.setPreferredSize(new java.awt.Dimension(49, 20));

        btnUserCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUserCancel.setText("Cancel");
        btnUserCancel.setMaximumSize(new java.awt.Dimension(71, 20));
        btnUserCancel.setMinimumSize(new java.awt.Dimension(71, 20));
        btnUserCancel.setPreferredSize(new java.awt.Dimension(71, 20));

        javax.swing.GroupLayout loginUserPanelLayout = new javax.swing.GroupLayout(loginUserPanel);
        loginUserPanel.setLayout(loginUserPanelLayout);
        loginUserPanelLayout.setHorizontalGroup(
            loginUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginUserPanelLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(loginUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginUserPanelLayout.createSequentialGroup()
                        .addComponent(btnUserOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnUserCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginUserPanelLayout.createSequentialGroup()
                        .addGroup(loginUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(loginUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUserPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtUserUser))))
                .addGap(27, 27, 27))
        );
        loginUserPanelLayout.setVerticalGroup(
            loginUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginUserPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(loginUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUserUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(loginUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUserCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserOK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        loginTabPanel.addTab("User", loginUserPanel);
        loginUserPanel.getAccessibleContext().setAccessibleName("");

        loginPanelMain.add(loginTabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 330, 220));

        getContentPane().add(loginPanelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GimsLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GimsLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GimsLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GimsLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GimsLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminCancel;
    private javax.swing.JButton btnAdminOk;
    private javax.swing.JButton btnUserCancel;
    private javax.swing.JButton btnUserOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblLock;
    private javax.swing.JPanel loginAdminPanel;
    private javax.swing.JPanel loginPanelMain;
    private javax.swing.JTabbedPane loginTabPanel;
    private javax.swing.JPanel loginUserPanel;
    private javax.swing.JPasswordField txtAdminPassword;
    private javax.swing.JTextField txtAdminUser;
    private javax.swing.JPasswordField txtUserPassword;
    private javax.swing.JTextField txtUserUser;
    // End of variables declaration//GEN-END:variables
}
