/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gims.design;

/**
 *
 * @author sukumar sen
 */
public class UniversityList extends javax.swing.JPanel {

    /**
     * Creates new form UniversityList
     */
    public UniversityList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstUniversity = new javax.swing.JList();
        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblUniversity = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstUniversity.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstUniversity);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 204, 170));

        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.setToolTipText("");
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 90, 40));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setToolTipText("");
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 90, 40));

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setToolTipText("");
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 90, 40));

        lblUniversity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUniversity.setForeground(new java.awt.Color(255, 255, 255));
        lblUniversity.setText("University List");
        add(lblUniversity, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 7, -1, 20));
        add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 20, 20));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblUniversity;
    private javax.swing.JList lstUniversity;
    // End of variables declaration//GEN-END:variables
}
